#!/usr/bin/env bash

# Parse a config file
function readconf() {
  while read line; do
    # skip comments
    [[ ${line:0:1} == "#" ]] && continue
 
    # skip empty lines
    [[ -z "$line" ]] && continue
 
    # eval the line
    eval $line
  done < "$1"
}

for wiki in `ls /etc/wikitrust/wikis_available.d`; do
  echo "Launching $wiki"
  CONFIG="/etc/wikitrust/wikis_available.d/$wiki"
  readconf $CONFIG
  echo "$DISPATCHER -db_user $DB_USER -db_name $DB_NAME -db_pass $DB_PASS -db_host $DB_HOST $OTHER_OPTIONS"

done
