#!/usr/bin/env bash

. /lib/lsb/init-functions

# Parse a config file
function readconf() {
  while read line; do
    # skip comments
    [[ ${line:0:1} == "#" ]] && continue
 
    # skip empty lines
    [[ -z "$line" ]] && continue
 
    # eval the line
    eval $line
  done < "$1"
}

for wiki in `ls /etc/wikitrust/wikis_enabled.d`; do
  #log_daemon_msg "--> Launching $wiki"
  echo -e "\t$wiki"
  config="/etc/wikitrust/wikis_enabled.d/$wiki"
  readconf $config
  DATE=`date +%Y%m%d`
  if [ -e $LOG_FILE ]; then
      mv $LOG_FILE "$LOG_FILE-$DATE"
  fi
  if [ -e $ERROR_FILE ]; then
      mv $ERROR_FILE "$ERROR_FILE-$DATE"
  fi
  touch $LOG_FILE
  touch $ERROR_FILE
  chmod a+w $LOG_FILE
  chmod a+w $ERROR_FILE
  nohup $USER "$DISPATCHER -db_user $DB_USER -db_name $DB_NAME -db_pass $DB_PASS -db_host $DB_HOST -log_file $LOG_FILE $OTHER_OPTIONS &" >> $LOG_FILE 2>> $ERROR_FILE < /dev/null
done

