#!/usr/bin/env bash

. /lib/lsb/init-functions

# Parse a config file
function readconf() {
  while read line; do
    # skip comments
    [[ ${line:0:1} == "#" ]] && continue
 
    # skip empty lines
    [[ -z "$line" ]] && continue
 
    # eval the line
    eval $line
  done < "$1"
}

for wiki in `ls /etc/wikitrust/wikis_enabled.d`; do
  #log_daemon_msg "--> Launching $wiki"
  config="/etc/wikitrust/wikis_enabled.d/$wiki"
  readconf $config
  touch $LOG_FILE
  touch $ERROR_FILE
  chmod a+w $LOG_FILE
  chmod a+w $ERROR_FILE
  $USER "$DISPATCHER -db_user $DB_USER -db_name $DB_NAME -db_pass $DB_PASS -db_host $DB_HOST -log_file $LOG_FILE $OTHER_OPTIONS" > $LOG_FILE 2> $ERROR_FILE &
done

