#!/usr/bin/perl
#
# Plugin to monitor WikiTrust usage.
#
# Usage: Place in /etc/munin/plugins (or link it there  using ln -s)
#
# Parameters understood:
#
# 	config   (required)
# 	autoconf (optional - used by munin-config)
#
# Magic markers - optional - used by installation scripts and
# munin-config:
#
#%# family=auto
#%# capabilities=autoconf

use LWP::Simple;
use File::Basename;

use constant URL => ".collaborativetrust.com:81/WikiTrust/RemoteAPI?method=status";
use constant SITES => qw( de fr it nl pl pt );

my $cmd = shift @ARGV;

my $lang =  basename($0);
$lang =~ s/^wikitrust_//;

if ($cmd eq "autoconf") {
    print "yes\n";
    exit(0);
}
if ($cmd eq "config") {
    print <<_EOT_;
graph_title WikiTrust Queue Size ($lang)
graph_args --base 1000 -r --lower-limit 0
graph_vlabel pages
graph_scale yes'
graph_info This graph shows how many pages are to be processed
graph_period minute
graph_category wikitrust
_EOT_
    print "pages.label $lang\n";
    print "elapsed.label $lang\n";
    exit(0);
}

getData($lang);
exit(0);

sub getData {
    use LWP::Simple;
    my $lang = shift @_;
    my $url = 'http://' . $lang . URL;
    my $content = get $url;
    print $content;
}
